### PR TITLE
Bump github.com/swaggo/swag v1.16.3

### PR DESCRIPTION
**Pull request by iredmail**
Note: Go 1.18 is required by swagger v1.16.3.
FYI https://github.com/swaggo/swag/releases/tag/v1.16.3

### CODE REVIEW

**Review by ReneWerner87 — APPROVED** [review]

**Comment by ReneWerner87** [comment]
@iredmail could you change the go.mod
`github.com/gofiber/swagger/v2` and readme

**Comment by iredmail** [comment]
> @iredmail could you change the go.mod `github.com/gofiber/swagger/v2` and readme

Latest version of v2 is [v2.0.0-rc3](https://github.com/swaggo/swag/releases/tag/v2.0.0-rc3), i suppose it's not "stable" and we should stay on v1 (v1.6.x) for now.

**Comment by ReneWerner87** [comment]
I actually meant that we should upgrade our swagger package to v2 because we are removing a golang version which is no longer supported and that is a breaking change

but since the package is still a v0 version, the change would also be okay and I change it to v1

**Comment by iredmail** [comment]
aha, sorry about the misunderstanding.

**Pull request merged**
