### PR TITLE
feature: Update swagger/files to version 2.0.0

### PR DESCRIPTION
**Pull request by Jictyvoo**
Update the  dependency version to 2.0.0, which uses embed to swagger files

### CODE REVIEW

**Review by efectn — APPROVED** [review]

**Comment by ReneWerner87** [comment]
Is there any breaking change included?

**Comment by ReneWerner87** [comment]
@Jictyvoo can you pls update with the master

**Comment by Jictyvoo** [comment]
> Is there any breaking change included?

The main change was the use of `swagger/files/v2` which started to use **go:embed** to "store" all swagger files. Before it used some kind of script to copy all files and store them as binaries inside go files.

On the middleware only this dependency and its use was changed

**Comment by Jictyvoo** [comment]
> @Jictyvoo can you pls update with the master

@ReneWerner87 Updated

**Pull request merged**
